server:
  port: 8080

filter:
  url:
    patterns: /pckart/api/v1/brands/auth/*,
              /pckart/api/v1/products/auth/*,
              /pckart/api/v1/categories/auth/*,
              /pckart/api/v1/banners/auth/*,

jwt:
  secret:
    key:
      products: ${JWT_SECRET_PRODUCTS}

cors:
  set:
    allowed:
      origins: ${CORS_1:http://localhost:4200},
               ${CORS_2:http://localhost:4401},
               ${CORS_3:https://silver-maamoul-f3f282.netlify.app},
               ${CORS_4:https://golden-duckanoo-61524b.netlify.app},
               ${CORS_5:http://localhost:4201},
               
               

